import React, { useEffect, useState } from 'react';
import { Navigate, useNavigate, useParams } from 'react-router-dom';
import Header from '../Header/Header';
import './Dealers.css';
const PostReview = () => {
  const {id}=useParams(); const navigate=useNavigate(); const [dealer,setDealer]=useState(null); const [cars,setCars]=useState([]);
  const [form,setForm]=useState({review:'',purchase_date:'',car:'',car_year:''}); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;Promise.all([fetch(`/djangoapp/dealer/${id}`),fetch('/djangoapp/get_cars')]).then(async([d,c])=>{const dd=await d.json(),cd=await c.json();if(!d.ok)throw new Error(dd.error||'Dealer not found.');if(!c.ok)throw new Error(cd.error||'Vehicles could not be loaded.');if(active){setDealer(dd.dealer?.[0]);setCars(cd.CarModels||[]);}}).catch((e)=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false};},[id]);
  if(!sessionStorage.getItem('username')) return <Navigate to="/login" replace/>;
  const submit=async(e)=>{e.preventDefault();setError('');const car=cars.find((item)=>`${item.CarMake}|${item.CarModel}|${item.CarYear}`===form.car);if(!car||!form.review.trim()||!form.purchase_date||!form.car_year)return setError('All review details are required.');setBusy(true);try{const res=await fetch('/djangoapp/add_review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dealership:Number(id),review:form.review.trim(),purchase:true,purchase_date:form.purchase_date,car_make:car.CarMake,car_model:car.CarModel,car_year:Number(form.car_year)})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Review could not be posted.');navigate(`/dealer/${id}`);}catch(err){setError(err.message);}finally{setBusy(false);}};
  return <><Header/><main className="auth-page">{loading?<div className="status-panel">Loading review form...</div>:<form className="auth-form review-form" onSubmit={submit}><p className="eyebrow">Share your experience</p><h1>Review {dealer?.full_name||'dealership'}</h1>{error&&<div className="form-message error" role="alert">{error}</div>}<label>Your review<textarea rows="6" value={form.review} onChange={(e)=>setForm({...form,review:e.target.value})}/></label><label>Purchase date<input type="date" value={form.purchase_date} onChange={(e)=>setForm({...form,purchase_date:e.target.value})}/></label><label>Vehicle<select value={form.car} onChange={(e)=>{const value=e.target.value;const car=cars.find((item)=>`${item.CarMake}|${item.CarModel}|${item.CarYear}`===value);setForm({...form,car:value,car_year:car?.CarYear||''})}}><option value="">Choose make and model</option>{cars.map((car)=><option key={`${car.CarMake}-${car.CarModel}-${car.CarYear}`} value={`${car.CarMake}|${car.CarModel}|${car.CarYear}`}>{car.CarMake} {car.CarModel} ({car.CarYear})</option>)}</select></label><label>Vehicle year<input type="number" min="2015" max="2030" value={form.car_year} onChange={(e)=>setForm({...form,car_year:e.target.value})}/></label><button className="primary-button" disabled={busy}>{busy?'Posting...':'Post review'}</button></form>}</main></>;
};
export default PostReview;
