services:
  mongo_db:
    image: mongo:7
    ports: ["27017:27017"]
    restart: always
    volumes: ["mongo_data:/data/db"]
  api:
    build: .
    image: dealership-database-api:local
    ports: ["3030:3030"]
    environment:
      MONGODB_URL: mongodb://mongo_db:27017/dealershipsDB
    depends_on: [mongo_db]
    restart: on-failure
volumes:
  mongo_data: {}
